### ISSUE TITLE
VRPTW算法的收敛问题

### ISSUE THREAD

**Issue by o0jingrui0o** [iRB-Lab/py-ga-VRPTW#1]
学长您好，偶然学习到您的程序，算法实现非常严谨。但有一个问题，观察您上传的result，感觉fitness随generation收敛速度有些慢，甚至感觉没有得到实质性的收敛，我初学可能理解不是很深刻，希望能得到您的指教。
BYR

**Comment by iROCKBUNNY** [comment]
你说的问题，我有注意到，这些问题出在参数调节的方面。
现有的程序只是把相关的算法实现了。目前并没有做调参的工作，所以现在的程序出来的结果并不是最好的。
调参的工作量比较大，需要跑大量的仿真程序，来尝试不同的遗传算子，以及每个遗传算子不同的参数设置。
