### ISSUE TITLE
Why do we evaluate individuals with invalid fitness?

### ISSUE THREAD

**Issue by zarifaziz** [iRB-Lab/py-ga-VRPTW#10]
Hi, first of all thank you for the well documented code - it has helped me a lot with my research project. I wanted to ask - in the `run_gavrptw()` function , why do we evaluate the individuals with invalid fitness?

It seems like you're trying to save the individuals with really bad fitness scores but I'm wondering why you're doing that. Thanks!

**Comment by iROCKBUNNY** [comment]
@zarifaziz Hey buddy! This algorithms used in the project is quite naiïve and requires tons of tunings. Since you have discovered the weakness of the this project, you may find out a way to improve the performance. Good luck!
