### ISSUE TITLE
Wrong max fitness value

### ISSUE THREAD

**Issue by radoslawik** [iRB-Lab/py-ga-VRPTW#11]
Hey, I have been trying the code and I discovered that max_fitness is not changing within number of generations. It makes the result always the same, even if there is only 1 generation. Firstly I was convinced that it can be library versioning or something connected to that, but the issue is also visible in the result csv's (max_fitness column does't seem to change).

**Comment by iROCKBUNNY** [comment]
Hey @radoslawik ! Thanks a lot. Can you fix it?

**Comment by radoslawik** [comment]
I have just noticed that my objection is the copy of #5 Performance Issue. The result is a random route that always seems to be is in initial population, even if population size is really small (for example 20).

**Comment by iROCKBUNNY** [comment]
@radoslawik The algorithm is not tuned and the performance is definitely poor. This was an experimental project. Please take it as a very fundamental (and far from robust) framework for your research work. With regards!
