### ISSUE TITLE
Unable to find a feasible solution for Solomons data sets

### ISSUE THREAD

**Issue by Kuifje02** [iRB-Lab/py-ga-VRPTW#12]
Hello,

I am trying to run the algorithm on all of Solomon's data sets to analyse the performance of the library. 

1. Are there existing benchmarks where I could find such results ?

2. I am unable to find feasible solutions. In particular, the routes that are computed violate the time windows (the arrival time is after the upper time window). I have tried setting a very high `delay_cost`, but this does not prevent the algorithm from violating the time windows (the due time). 

Thanks for your help!

**Comment by iROCKBUNNY** [comment]
@Kuifje02 Hello Romain,

Sorry, I should have answered this a week ago. I have noticed that you have done serious jobs.

1. As far as I know, there is no such benchmarks or results.
2. You are right. I am afraid that this project is not even close to a robust solution. However, the implemented algorithm is quite simple (at least to me). Maybe you could dig into the source code to discover some vulnerabilities and perform some improvements. 

I do hope you do well in your project!
