### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by 2860166** [iRB-Lab/py-ga-VRPTW#15]
Hi. what is the unit of time windows? is it second or hour? and why we need service time? can we ignore it?

**Comment by HuangYanfei** [comment]
It doesn't matter of the unit in this setting, as long as it's the same as the distance's. The service time is also a common setting of VRPTW, u can check it out on the Solomon benchmark(https://www.sintef.no/projectweb/top/vrptw/solomon-benchmark/documentation/)
