### ISSUE TITLE
Improve GA performance

### ISSUE THREAD

**Issue by paulliwali** [iRB-Lab/py-ga-VRPTW#8]
Hello, first of all thank you for the repo as it provided a great starting point for me to adapt the GA procedure to solve VRP with movement synchronizations. From my experience, I find that using an elite selection process will help improve your code performance. So I used the built-in elite selection function from `deap` - `selBest()` and keep that individual to the next generation. You can elite select x% of the percentage as you see fit. 

Another thing is I found there was a small error with your implementation of the PMX function, I suggest use the built in one from `deap` but make a small modification to the indexing to account for the depot number convention. This will make the PMX function work as intended and create better offsprings. With these two changes implmented, it can converge VRP solutions very quickly.

Sorry that I am writing this as an issue as opposed to making a pull request. I am fairly new to git and I didn't know which is the more efficient way when I already made a fork but committed too many changes that are not relevant to your repo anymore. 

Let me know if I can still make a pull-request and help you improve this awesome repo.

**Comment by iROCKBUNNY** [comment]
@paulliwali Thanks for your advice! As I have mentioned in the docs, this repo starts as a course project and the algorithms were designed for certain circumstances. I already labeled your repo as **outstanding** in the `README.md` file, hence demanding no further pulls for the moment. Maybe I can add some detailed endorsement about the significant improvements you have accomplished to my `README.md` file when I get a slot. 

Anyway, thanks for your contribution to filling up the missing of common solutions - the VRPTW GA Python common solutions - in the massive open source community. Hope it grow much stronger in the future.

**Comment by softzer0** [comment]
It would be awesome that these two projects could be merged for once. I'd be much grateful for that. :)
